; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -verify-machineinstrs < %s | FileCheck -check-prefix=GFX11 %s

define amdgpu_vs void @tbuffer_store_merge_test(<4 x i32> inreg %rsrc, i32 inreg %vid) {
; GFX11-LABEL: tbuffer_store_merge_test:
; GFX11:       ; %bb.0: ; %entry
; GFX11-NEXT:    v_dual_mov_b32 v0, 1.0 :: v_dual_mov_b32 v1, s4
; GFX11-NEXT:    v_dual_mov_b32 v2, 2.0 :: v_dual_mov_b32 v3, 0x40a00000
; GFX11-NEXT:    v_mov_b32_e32 v6, 0x40c00000
; GFX11-NEXT:    v_dual_mov_b32 v4, 0x40400000 :: v_dual_mov_b32 v5, 4.0
; GFX11-NEXT:    s_clause 0x1
; GFX11-NEXT:    tbuffer_store_format_x v0, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen
; GFX11-NEXT:    tbuffer_store_format_x v3, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:16
; GFX11-NEXT:    v_mov_b32_e32 v0, 0x40e00000
; GFX11-NEXT:    v_mov_b32_e32 v3, 0x41000000
; GFX11-NEXT:    s_clause 0x5
; GFX11-NEXT:    tbuffer_store_format_x v2, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:2
; GFX11-NEXT:    tbuffer_store_format_x v6, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:18
; GFX11-NEXT:    tbuffer_store_format_x v4, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:4
; GFX11-NEXT:    tbuffer_store_format_x v0, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:20
; GFX11-NEXT:    tbuffer_store_format_x v5, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:6
; GFX11-NEXT:    tbuffer_store_format_x v3, v1, s[0:3], 0 format:[BUF_FMT_16_FLOAT] idxen offset:22
; GFX11-NEXT:    s_endpgm
entry:
  %rsrc.v4 = bitcast <4 x i32> %rsrc to <4 x i32>
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1065353216, <4 x i32> %rsrc.v4, i32 %vid, i32 0,  i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1073741824, <4 x i32> %rsrc.v4, i32 %vid, i32 2,  i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1077936128, <4 x i32> %rsrc.v4, i32 %vid, i32 4,  i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1082130432, <4 x i32> %rsrc.v4, i32 %vid, i32 6,  i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1084227584, <4 x i32> %rsrc.v4, i32 %vid, i32 16, i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1086324736, <4 x i32> %rsrc.v4, i32 %vid, i32 18, i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1088421888, <4 x i32> %rsrc.v4, i32 %vid, i32 20, i32 0, i32 13, i32 0)
  call void @llvm.amdgcn.struct.tbuffer.store.i32(i32 1090519040, <4 x i32> %rsrc.v4, i32 %vid, i32 22, i32 0, i32 13, i32 0)

  ret void
}

declare void @llvm.amdgcn.struct.tbuffer.store.i32(i32, <4 x i32>, i32, i32, i32, i32, i32)
